# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winners65OutOf100Fee13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1', models.IntegerField(default=60)),
                ('Rank2', models.IntegerField(default=45)),
                ('Rank3', models.IntegerField(default=35)),
                ('Rank4To5', models.IntegerField(default=25)),
                ('Rank6To25', models.IntegerField(default=20)),
                ('Rank26To40', models.IntegerField(default=14)),
                ('Rank41To65', models.IntegerField(default=8)),
            ],
        ),
    ]
