# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners20OutOf35Fee49',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1', models.IntegerField(default=400)),
                ('Rank2', models.IntegerField(default=200)),
                ('Rank3', models.IntegerField(default=100)),
                ('Rank4To5', models.IntegerField(default=75)),
                ('Rank6To10', models.IntegerField(default=50)),
                ('Rank11To20', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Winners25OutOf100Fee12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1', models.IntegerField(default=200)),
                ('Rank2', models.IntegerField(default=100)),
                ('Rank3', models.IntegerField(default=75)),
                ('Rank4To5', models.IntegerField(default=50)),
                ('Rank6To10', models.IntegerField(default=35)),
                ('Rank11To20', models.IntegerField(default=25)),
                ('Rank21To25', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Winners25OutOf40Fee31',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1', models.IntegerField(default=250)),
                ('Rank2', models.IntegerField(default=125)),
                ('Rank3', models.IntegerField(default=80)),
                ('Rank4To5', models.IntegerField(default=50)),
                ('Rank6To10', models.IntegerField(default=40)),
                ('Rank11To25', models.IntegerField(default=23)),
            ],
        ),
        migrations.CreateModel(
            name='Winners2OutOf5Fee23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1', models.IntegerField(default=60)),
                ('Rank2', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Winners3OutOf10Fee53',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1', models.IntegerField(default=250)),
                ('Rank2', models.IntegerField(default=150)),
                ('Rank3', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Winners40OutOf100Fee12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1', models.IntegerField(default=150)),
                ('Rank2', models.IntegerField(default=100)),
                ('Rank3', models.IntegerField(default=60)),
                ('Rank4To5', models.IntegerField(default=40)),
                ('Rank6To10', models.IntegerField(default=30)),
                ('Rank11To20', models.IntegerField(default=20)),
                ('Rank21To40', models.IntegerField(default=13)),
            ],
        ),
        migrations.RenameModel(
            old_name='Winners65OutOf100Fee13',
            new_name='Winners65OutOf100Fee12',
        ),
    ]
