# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_matches', '0002_auto_20190509_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners1To3OutOf10Fee53',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1To3', models.IntegerField(default=167)),
            ],
        ),
    ]
