# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_matches', '0003_winners1to3outof10fee53'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free100To10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1To10', models.IntegerField(default=10)),
            ],
        ),
    ]
