# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_matches', '0004_free100to10'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners2OutOf4Fee55Equal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1To2', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Winners2OutOf5Fee11Equal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1To2', models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='Winners2OutOf5Fee21Equal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank1To2', models.IntegerField(default=50)),
            ],
        ),
    ]
