"""
Django settings for FancyChamps project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from decouple import config


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
STATICFILES = os.path.join(BASE_DIR, 'static')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

SITE_ID = 1

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = [config('ALLOWED_HOST'),]


# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_user_agents',
    'widget_tweaks',
    'accounts',
    'cricket_center',
    'cricket_matches',
    'payments',
    'support',
    'kabaddi_center',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django_smtp_ssl'
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    # 'FancyChamps.CustomMiddlewares.StackOverflowMiddleware'
]

ROOT_URLCONF = 'FancyChamps.urls'
#Middleware Settings :
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# X_FRAME_OPTIONS = 'DENY'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FancyChamps.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

#For SQLITE3
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'db.sqlite3',
#     }
# }
#For MySQL
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'FightBack$TestFancyChampsDB',
#         'USER': 'FightBack',
#         'PASSWORD': '2010rahul',
#         'HOST': 'FightBack.mysql.pythonanywhere-services.com',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         }
#     }
# }

# For Postgresql
if DEBUG == False:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER_NAME'),
            'PASSWORD': config('DB_USER_PASS'),
            'HOST': config('DB_HOST'),
            'PORT': '',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'db.sqlite3',
        }
    }
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.postgresql',
    #         'NAME': config('DB_NAME'),
    #         'USER': config('DB_USER_NAME'),
    #         'PASSWORD': config('DB_USER_PASS'),
    #         'HOST': config('DB_HOST'),
    #         'PORT': '11141',
    #     }
    # }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/


TIME_ZONE = 'Asia/Kolkata'

LANGUAGE_CODE = 'en-us'
USE_I18N = True

USE_L10N = True

USE_TZ = True

DATE_INPUT_FORMATS = ('%d/%m/%Y')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    STATICFILES,
]

STATIC_ROOT = os.path.join(BASE_DIR, 'ProductionFiles')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_USE_SSL = config("SMTP_SSL")
EMAIL_PORT = config("EMAIL_PORT")

DEFAULT_FROM_EMAIL = 'FancyChampes Verification <verify@fancychamps.com>'

CSRF_FAILURE_VIEW = 'FancyChamps.views.csrf_failure'

# Paytm Crudentials#
PAYTM_MERCHANT_KEY = config("MERCHANT_KEY")#"#TNO3hVA_FZMjgBF"
PAYTM_MERCHANT_ID = config("MERCHANT_ID")#"QSvNWW73814951846758"
HOST_URL = config("HOST_URL")
PAYTM_CALLBACK_URL = "/payments/response/"
PAYTM_WEBSITE = config("PAYTM_WEBSITE")
if DEBUG:
    PAYTM_MERCHANT_KEY = config("MERCHANT_KEY")#"#TNO3hVA_FZMjgBF"
    PAYTM_MERCHANT_ID = config("MERCHANT_ID")#"QSvNWW73814951846758"
    PAYTM_WEBSITE = config("PAYTM_WEBSITE")#'WEBSTAGING'
    HOST_URL = config("HOST_URL")

#https://securegw-stage.paytm.in/theia/processTransaction