# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_send_detail',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='otpverificationemail',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='otpverificationemail',
            name='otp_send',
            field=models.CharField(max_length=10),
        ),
    ]
