# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
