# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_is_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contest_played',
            field=models.IntegerField(default=0),
        ),
    ]
