# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_contest_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
        ),
    ]
