# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190623_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=255)),
                ('failed_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
