# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=100)),
                ('tournament_name', models.CharField(max_length=50)),
                ('match_date', models.DateTimeField()),
                ('match_tick', models.IntegerField(blank=True)),
                ('match_slug', models.CharField(default='Test', max_length=64, unique=True)),
                ('team_one', models.CharField(max_length=25)),
                ('team_two', models.CharField(max_length=25)),
                ('team_one_image', models.CharField(max_length=25)),
                ('team_two_image', models.CharField(max_length=25)),
                ('history_activate', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('short_team_one', models.CharField(default='IND', max_length=5)),
                ('short_team_two', models.CharField(default='AUS', max_length=5)),
                ('initial_contest_created', models.BooleanField(default=False)),
                ('match_status', models.CharField(default='0/0 (0 Overs)', max_length=255)),
            ],
        ),
    ]
