# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabaddi_center', '0003_auto_20190727_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='INDPALTeam',
            new_name='INDPAKTeam',
        ),
    ]
