# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kabaddi_center', '0004_auto_20190727_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=100)),
                ('contest_slug', models.CharField(default='Test', max_length=64, unique=True)),
                ('contest_prize', models.IntegerField()),
                ('contest_fee', models.IntegerField()),
                ('contest_size', models.IntegerField()),
                ('contest_winners', models.IntegerField(default=1)),
                ('total_player_joined', models.IntegerField()),
                ('joined_percentage', models.IntegerField(default=0)),
                ('contest_category', models.CharField(max_length=100)),
                ('multiple_entry', models.BooleanField(default=False)),
                ('multiple_entry_text', models.CharField(blank=True, default='', max_length=5)),
                ('filled_status', models.BooleanField(default=False)),
                ('bonus_contest', models.BooleanField(default=False)),
                ('bonus_contest_text', models.CharField(blank=True, default='', max_length=5)),
                ('free_contest', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_text', models.CharField(blank=True, default='', max_length=5)),
                ('prize_dist_type', models.CharField(max_length=100)),
                ('bonus_percent', models.IntegerField(default=0)),
                ('cancelled', models.BooleanField(default=False)),
                ('contest_of_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kabaddi_center.MatchDetail')),
            ],
        ),
    ]
