# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaddi_center', '0005_contestdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_user', models.CharField(max_length=255)),
                ('joined_contest_slug', models.CharField(max_length=255)),
                ('joined_user_team', models.CharField(max_length=255)),
                ('match_slug', models.CharField(default='', max_length=255)),
                ('total_team_points', models.FloatField(default=0.0)),
                ('winnings', models.FloatField(default=0.0)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('bonus_deduction', models.PositiveIntegerField(default=0)),
                ('balance_deduction', models.PositiveIntegerField(default=0)),
                ('winnings_deduction', models.PositiveIntegerField(default=0)),
                ('last_rank', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
