# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaddi_center', '0006_joiningdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=255)),
                ('player_current_team', models.CharField(default='', max_length=25)),
                ('player_type', models.CharField(default='Keeper/Batsman/Allrounder/Bowler', max_length=25)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('player_credit_points', models.DecimalField(decimal_places=1, default=7.5, max_digits=3)),
                ('current_points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
