# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabaddi_center', '0007_playerdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='INDPAKTeam',
            new_name='PATTAMTeam',
        ),
    ]
