# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabaddi_center', '0008_auto_20190728_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattamteam',
            old_name='total_defender',
            new_name='total_defenders',
        ),
    ]
