# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaddi_center', '0009_auto_20190728_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningTransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('transaction_amt', models.IntegerField(default=0)),
                ('transact_user', models.CharField(max_length=64)),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('transaction_message', models.CharField(default='', max_length=255)),
                ('transaction_type', models.CharField(default='added', max_length=16)),
                ('refund_for_contest', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
