# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabaddi_center', '0010_joiningtransactiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_slug', models.CharField(max_length=512)),
                ('message', models.CharField(max_length=512)),
                ('user', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
