# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabaddi_center', '0011_contestmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PATTAMTeam',
            new_name='PATJAITeam',
        ),
    ]
