# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreTransData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=64)),
                ('url_called', models.CharField(max_length=25)),
                ('transact_user', models.CharField(max_length=64)),
                ('checksum', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('transaction_amt', models.IntegerField(default=0)),
                ('transaction_status', models.CharField(max_length=25)),
                ('transact_user', models.CharField(max_length=64)),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('captured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionFailedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('transaction_amt', models.IntegerField(default=0)),
                ('transaction_status', models.CharField(max_length=25)),
                ('transact_user', models.CharField(max_length=64)),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('captured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WidhdrawRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('widhdraw_amount', models.CharField(max_length=64)),
                ('request_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
