# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretransdata',
            name='order_id',
            field=models.CharField(max_length=32),
        ),
    ]
