# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190429_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretransdata',
            name='checksum',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pretransdata',
            name='order_id',
            field=models.CharField(max_length=64),
        ),
    ]
