# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190429_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfaileddetail',
            name='added_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
