# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transactionfaileddetail_added_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionfaileddetail',
            name='added_to_user',
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='added_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
