# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20190508_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
