# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20190508_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction_message',
            field=models.CharField(default='Money Added', max_length=255),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction_type',
            field=models.CharField(default='added', max_length=16),
        ),
    ]
