# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20190606_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='requested_contest_slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
