# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_transactiondetail_requested_contest_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='requested_contest_slug',
            new_name='requested_match_slug',
        ),
    ]
