# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=100)),
                ('contest_slug', models.CharField(default='Test', max_length=64, unique=True)),
                ('contest_prize', models.IntegerField()),
                ('contest_fee', models.IntegerField()),
                ('contest_size', models.IntegerField()),
                ('contest_winners', models.IntegerField(default=1)),
                ('total_player_joined', models.IntegerField()),
                ('joined_percentage', models.IntegerField(default=0)),
                ('contest_category', models.CharField(max_length=100)),
                ('multiple_entry', models.BooleanField(default=False)),
                ('filled_status', models.BooleanField(default=False)),
                ('bonus_contest', models.BooleanField(default=False)),
                ('free_contest', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('prize_dist_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContestMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_slug', models.CharField(max_length=512)),
                ('message', models.CharField(max_length=512)),
                ('user', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoiningDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_user', models.CharField(max_length=255)),
                ('joined_contest_slug', models.CharField(max_length=255)),
                ('joined_user_team', models.CharField(max_length=255)),
                ('match_slug', models.CharField(default='', max_length=255)),
                ('total_team_points', models.FloatField(default=0.0)),
                ('winnings', models.FloatField(default=0.0)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('bonus_deduction', models.PositiveIntegerField(default=0)),
                ('main_deduction', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JoiningTransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('transaction_amt', models.IntegerField(default=0)),
                ('transact_user', models.CharField(max_length=64)),
                ('transaction_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=100)),
                ('tournament_name', models.CharField(max_length=25)),
                ('match_date', models.DateTimeField()),
                ('match_tick', models.IntegerField(blank=True)),
                ('match_slug', models.CharField(default='Test', max_length=64, unique=True)),
                ('team_one', models.CharField(max_length=25)),
                ('team_two', models.CharField(max_length=25)),
                ('team_one_image', models.CharField(max_length=25)),
                ('team_two_image', models.CharField(max_length=25)),
                ('history_activate', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('short_team_one', models.CharField(default='IND', max_length=5)),
                ('short_team_two', models.CharField(default='AUS', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=255)),
                ('player_current_team', models.CharField(default='', max_length=25)),
                ('player_type', models.CharField(default='Keeper/Batsman/Allrounder/Bowler', max_length=25)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('player_credit_points', models.DecimalField(decimal_places=1, default=7.5, max_digits=3)),
                ('current_points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='contestdetail',
            name='contest_of_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_center.MatchDetail'),
        ),
    ]
