# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0004_banireteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='wibanteam',
            name='Keeper_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wibanteam',
            name='Player10_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wibanteam',
            name='Player11_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wibanteam',
            name='Player2_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wibanteam',
            name='Player3_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wibanteam',
            name='Player4_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wibanteam',
            name='Player5_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wibanteam',
            name='Player6_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wibanteam',
            name='Player7_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wibanteam',
            name='Player8_Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wibanteam',
            name='Player9_Points',
            field=models.IntegerField(default=0),
        ),
    ]
