# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0011_slsateam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AFGSCOTeam',
        ),
        migrations.DeleteModel(
            name='BANIRETeam',
        ),
        migrations.DeleteModel(
            name='CSKDCTeam',
        ),
        migrations.DeleteModel(
            name='CSKMITeam',
        ),
        migrations.DeleteModel(
            name='ENGPAKTeam',
        ),
        migrations.DeleteModel(
            name='MICSKTeam',
        ),
        migrations.DeleteModel(
            name='SRHDCTeam',
        ),
        migrations.DeleteModel(
            name='WIBANTeam',
        ),
    ]
