# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0013_indnzteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdetail',
            name='tournament_name',
            field=models.CharField(max_length=50),
        ),
    ]
