# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-01 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0018_nzslteam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='INDNZTeam',
            new_name='SABANTeam',
        ),
    ]
