# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-01 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0019_auto_20190601_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiningtransactiondetail',
            name='transaction_message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joiningtransactiondetail',
            name='transaction_type',
            field=models.CharField(default='added', max_length=16),
        ),
    ]
