# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0020_auto_20190602_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joiningdetail',
            old_name='main_deduction',
            new_name='balance_deduction',
        ),
        migrations.AddField(
            model_name='contestdetail',
            name='bonus_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joiningdetail',
            name='winnings_deduction',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
