# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0023_indsateam'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestdetail',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
