# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0025_engbanteam_nzagfteam_slpakteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestdetail',
            name='bonus_contest_text',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='contestdetail',
            name='confirmed_text',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='contestdetail',
            name='multiple_entry_text',
            field=models.CharField(default='', max_length=5),
        ),
    ]
