# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0026_auto_20190608_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestdetail',
            name='bonus_contest_text',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='contestdetail',
            name='confirmed_text',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='contestdetail',
            name='multiple_entry_text',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
