# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0029_indausteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetail',
            name='initial_contest_created',
            field=models.BooleanField(default=False),
        ),
    ]
