# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0034_indpakteam_saafgteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetail',
            name='match_status',
            field=models.CharField(default='0/0 (0 Overs)', max_length=255),
        ),
    ]
