# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0041_zimnedteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiningdetail',
            name='last_rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
