# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0049_afgwiteam_engnzteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AFGBANTeam',
        ),
        migrations.DeleteModel(
            name='AFGWITeam',
        ),
        migrations.DeleteModel(
            name='AUSBANTeam',
        ),
        migrations.DeleteModel(
            name='AUSNZTeam',
        ),
        migrations.DeleteModel(
            name='AUSSLTeam',
        ),
        migrations.DeleteModel(
            name='ENGAFGTeam',
        ),
        migrations.DeleteModel(
            name='ENGNZTeam',
        ),
        migrations.DeleteModel(
            name='ENGSATeam',
        ),
        migrations.DeleteModel(
            name='ENGSLTeam',
        ),
        migrations.DeleteModel(
            name='INDAFGTeam',
        ),
        migrations.DeleteModel(
            name='INDBANTeam',
        ),
        migrations.DeleteModel(
            name='INDENGTeam',
        ),
        migrations.DeleteModel(
            name='INDPAKTeam',
        ),
        migrations.DeleteModel(
            name='INDWITeam',
        ),
        migrations.DeleteModel(
            name='NEDZIMTeam',
        ),
        migrations.DeleteModel(
            name='NZAFGTeam',
        ),
        migrations.DeleteModel(
            name='NZPAKTeam',
        ),
        migrations.DeleteModel(
            name='NZSATeam',
        ),
        migrations.DeleteModel(
            name='PAKAFGTeam',
        ),
        migrations.DeleteModel(
            name='PAKSATeam',
        ),
        migrations.DeleteModel(
            name='SAAFGTeam',
        ),
        migrations.DeleteModel(
            name='SLSATeam',
        ),
        migrations.DeleteModel(
            name='SLWITeam',
        ),
        migrations.DeleteModel(
            name='WIENGTeam',
        ),
        migrations.DeleteModel(
            name='ZIMNEDTeam',
        ),
    ]
