# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0053_engausteam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ENGAUSTeam',
            new_name='ENGNZTeam',
        ),
    ]
