# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0054_auto_20190712_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiningtransactiondetail',
            name='refund_for_contest',
            field=models.CharField(default='', max_length=255),
        ),
    ]
