# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-24 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0063_tutlycteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='banslteam',
            name='team_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='karvbkteam',
            name='team_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tutlycteam',
            name='team_no',
            field=models.IntegerField(default=1),
        ),
    ]
