# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0072_wsllteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AUSENGTeam',
        ),
        migrations.DeleteModel(
            name='BANSLTeam',
        ),
        migrations.DeleteModel(
            name='CHEDINTeam',
        ),
        migrations.DeleteModel(
            name='DINKARTeam',
        ),
        migrations.DeleteModel(
            name='ENGNZTeam',
        ),
        migrations.DeleteModel(
            name='INDAWIATeam',
        ),
        migrations.DeleteModel(
            name='INDNZTeam',
        ),
        migrations.DeleteModel(
            name='INDWITeam',
        ),
        migrations.DeleteModel(
            name='IREZIMTeam',
        ),
        migrations.DeleteModel(
            name='KARCHETeam',
        ),
        migrations.DeleteModel(
            name='KARVBKTeam',
        ),
        migrations.DeleteModel(
            name='LYCRUBTeam',
        ),
        migrations.DeleteModel(
            name='RUBCHETeam',
        ),
        migrations.DeleteModel(
            name='RUBKARTeam',
        ),
        migrations.DeleteModel(
            name='SLBANTeam',
        ),
        migrations.DeleteModel(
            name='TUTLYCTeam',
        ),
        migrations.DeleteModel(
            name='TUTMADTeam',
        ),
    ]
