# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-06 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0074_indwiteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiningdetail',
            name='added_to_wallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joiningdetail',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joiningtransactiondetail',
            name='transaction_for_contest',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matchdetail',
            name='added_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchdetail',
            name='cancelled_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchdetail',
            name='refund_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchdetail',
            name='update_wins_called',
            field=models.BooleanField(default=False),
        ),
    ]
