# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0076_wsltteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WSLTTeam',
        ),
    ]
