# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 14:05
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_center', '0077_delete_wsltteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSLTTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keeper', models.CharField(default='', max_length=255)),
                ('Player2', models.CharField(default='', max_length=255)),
                ('Player3', models.CharField(default='', max_length=255)),
                ('Player4', models.CharField(default='', max_length=255)),
                ('Player5', models.CharField(default='', max_length=255)),
                ('Player6', models.CharField(default='', max_length=255)),
                ('Player7', models.CharField(default='', max_length=255)),
                ('Player8', models.CharField(default='', max_length=255)),
                ('Player9', models.CharField(default='', max_length=255)),
                ('Player10', models.CharField(default='', max_length=255)),
                ('Player11', models.CharField(default='', max_length=255)),
                ('Captain', models.CharField(default=' ', max_length=255)),
                ('Vice_Captain', models.CharField(default=' ', max_length=255)),
                ('Keeper_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Player2_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Player3_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Player4_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Player5_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Player6_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Player7_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Player8_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Player9_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Player10_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Player11_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Captain_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('Vice_Captain_Points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_batsmen', models.IntegerField(default=4)),
                ('total_allrounders', models.IntegerField(default=3)),
                ('total_bowlers', models.IntegerField(default=3)),
                ('team_no', models.IntegerField(default=1)),
                ('username_of_player', models.CharField(max_length=64)),
                ('total_credits_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('match_slug', models.CharField(max_length=100)),
                ('full_team_name', models.CharField(default='Something', max_length=255)),
            ],
        ),
    ]
